name = "raynetwork-io"
type = "webpack"
account_id = "792461088a4c863230f3faee467094b1"
# workers_dev = true
route = "raynetwork.io/*"
zone_id = "55735576058a638a71d3c8f08122703d"

[site]
bucket = "../public"
entry-point = "workers-site"
