const actions = {
  SET_STATE: "settings/SET_STATE",
  CHANGE_SETTING: "settings/CHANGE_SETTING",
  CHANGE_THEME: "settings/CHANGE_THEME",
  SWITCH_MEGA_MENU: "settings/SWITCH_MEGA_MENU",
  FETCH_NETWORK_STATE: "settings/FETCH_NETWORK_STATE",
  FETCH_STAGE1_HISTORY: "settings/FETCH_STAGE1_HISTORY",
  FETCH_PRICES: "settings/FETCH_PRICES",
}

export default actions
